<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KingImg</AssemblyName>
    <RootNamespace>KingImg</RootNamespace>
    <Version>1.1.0</Version>
    <Company>Vien Nguyen</Company>
    <Product>King Img</Product>
    <Authors>Vien Nguyen</Authors>
    <Copyright>© 2026 Vien Nguyen</Copyright>
    <ApplicationIcon>build\icon.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2739.15" />
    <PackageReference Include="PdfSharp" Version="6.2.4" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="renderer\**\*">
      <LogicalName>renderer/%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="fonts-bundled\**\*">
      <LogicalName>fonts-bundled/%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
